# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'Fit Tip App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fit Tip App
pod 'lottie-ios'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SkyFloatingLabelTextField'
pod 'DropDown'
pod 'Charts'
pod 'TinyConstraints'

end
