# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EsayFlight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EsayFlight
pod 'Firebase/Analytics'	
pod 'Firebase/Auth'	
pod 'Firebase/Firestore'
pod 'DropDown'

 pod 'GoogleMaps', '5.2.0'	
end
