# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tuwaiq 1000' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tuwaiq 1000
    pod 'Firebase/Firestore'
    pod  'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'MessageUI'

    

end
