# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eBook
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'PDFReader'
   pod 'Firebase/Storage'
   pod 'Firebase/Database'


end
